services:
  - type: web
    name: resume-tailor
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_VERSION
        value: gpt-4o-mini
      - key: NODE_ENV
        value: production

